apiVersion: v1
kind: Service

metadata:
  name: python-greetcode-service

spec:
  type: NodePort

  selector:
    app: python-greetcode

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007